/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue,mjs}"],
  theme: {
    extend: {
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
        mono: ["JetBrains Mono Variable", "JetBrains Mono", "monospace"],
      },
      colors: {
        "primary": "#9e4a5c",
        "primary-dim": "#8a3d4f",
        "primary-container": "#ffc0c0",
        "on-primary": "#fff0ef",
        "on-primary-container": "#6e2840",
        "on-primary-fixed": "#4e1528",
        "on-primary-fixed-variant": "#7a3348",
        "primary-fixed": "#ffc0c0",
        "primary-fixed-dim": "#f0a8a8",
        "inverse-primary": "#ffc0c0",
        "secondary": "#a03742",
        "secondary-dim": "#902b37",
        "secondary-container": "#ffc3c4",
        "on-secondary": "#ffefef",
        "on-secondary-container": "#852230",
        "on-secondary-fixed": "#6a0c1e",
        "on-secondary-fixed-variant": "#912c38",
        "secondary-fixed": "#ffc3c4",
        "secondary-fixed-dim": "#ffaeb2",
        "tertiary": "#b0546e",
        "tertiary-dim": "#9e4560",
        "tertiary-container": "#f5b8c8",
        "on-tertiary": "#fff0f3",
        "on-tertiary-container": "#6e2840",
        "on-tertiary-fixed": "#4a1028",
        "on-tertiary-fixed-variant": "#8a3855",
        "tertiary-fixed": "#f5b8c8",
        "tertiary-fixed-dim": "#e8a0b4",
        "background": "#fff4f3",
        "on-background": "#3b2b29",
        "surface": "#fff4f3",
        "on-surface": "#3b2b29",
        "on-surface-variant": "#6a5755",
        "surface-variant": "#f7d5d2",
        "surface-dim": "#efcdc9",
        "surface-bright": "#fff4f3",
        "surface-tint": "#7e4f46",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#ffedeb",
        "surface-container": "#ffe2de",
        "surface-container-high": "#fbdbd8",
        "surface-container-highest": "#f7d5d2",
        "outline": "#877270",
        "outline-variant": "#c0a8a5",
        "error": "#b41340",
        "error-dim": "#a70138",
        "error-container": "#f74b6d",
        "on-error": "#ffefef",
        "on-error-container": "#510017",
        "inverse-surface": "#170b0a",
        "inverse-on-surface": "#af9895",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
}
